// src/data/events.js
const events = [
  {
    id: 1,
    type: "custom",
    image:
      "https://hiu.vn/wp-content/uploads/2023/02/z4079030922121_5c7c9db54a32aeca0315e93b99e23e2e-1-2-2-870x285.jpg",
    title: "Cuộc thi Lịch sử Đảng Cộng sản VN",
    time: "2025-06-10T09:00:00",
    location: "Hội trường A, HIU",
    description: "Khám phá lịch sử, săn 3 ĐRL!",
    eventType: "Cuộc thi",
    audience: "Sinh viên",
    readMoreUrl: "#",
    tags: ["học tập", "cuộc thi", "đrl"],
    drlCriteria: "Hoạt động xã hội",
    drlPoints: 3,
    hasSeating: true,
    availableSeats: 50
  },
  {
    id: 2,
    type: "custom",
    image: "https://hiu.vn/wp-content/uploads/2023/03/DSC03048-800x285.jpg",
    title: "Giao lưu cùng CEO",
    time: "2025-06-15T14:00:00",
    location: "Hội trường Beethoven, HIU",
    description: "Học bí kíp khởi nghiệp từ CEO!",
    eventType: "Talkshow",
    audience: "Sinh viên",
    readMoreUrl:
      "https://hiu.vn/hiu-student-center/sinh-vien-hiu-hao-hung-giao-luu-cung-cac-sep/",
    tags: ["học tập", "kỹ năng", "khởi nghiệp", "đrl"],
    drlCriteria: "Kỹ năng chuyên môn",
    drlPoints: 2,
    hasSeating: true,
    availableSeats: 0 // Cháy vé
  },
  {
    id: 3,
    type: "custom",
    image: "https://hiu.vn/wp-content/uploads/2022/12/thumnail-800x285.jpg",
    title: "Hội nghị Công nghệ HIU",
    time: "2025-06-20T08:00:00",
    location: "Hội trường A, HIU",
    description: "Cập nhật công nghệ, nhận 3 ĐRL!",
    eventType: "Hội thảo",
    audience: "Sinh viên",
    readMoreUrl:
      "https://hiu.vn/hiu-student-center/chuong-trinh-hoi-nghi-khoa-hoc-cong-nghe-hiu-mo-rong/",
    tags: ["học tập", "cntt", "đrl"],
    drlCriteria: "Học tập",
    drlPoints: 3,
    hasSeating: true,
    availableSeats: 20
  },
  {
    id: 4,
    type: "custom",
    image:
      "https://hiu.vn/wp-content/uploads/2025/05/thum-ngay-hoi-quoc-te-dieu-duong-hiu-2025-800x285.jpg",
    title: "Ngày Quốc tế Điều dưỡng",
    time: "2025-06-25T09:00:00",
    location: "Hội trường Beethoven, HIU",
    description: "Tôn vinh điều dưỡng, lan tỏa yêu thương!",
    eventType: "Hoạt động đoàn thể",
    audience: "Sinh viên",
    readMoreUrl:
      "https://hiu.vn/hiu-student-center/ngay-quoc-te-dieu-duong-2025-sinh-vien-hiu-tiep-lua-florence-nightingale/",
    tags: ["thiện nguyện", "y khoa", "đrl"],
    drlCriteria: "Hoạt động xã hội",
    drlPoints: 3,
    hasSeating: true,
    availableSeats: 0 // Cháy vé
  },
  {
    id: 5,
    type: "custom",
    image: "https://hiu.vn/wp-content/uploads/2024/12/2-870x285.jpg",
    title: "Chung kết Olympic Tiếng Anh",
    time: "2025-07-01T09:00:00",
    location: "Hội trường Beethoven, HIU",
    description: "Tranh tài Tiếng Anh, săn 4 ĐRL!",
    eventType: "Cuộc thi",
    audience: "Sinh viên",
    readMoreUrl:
      "https://hiu.vn/hiu-student-center/chuc-mung-vong-chung-ket-olympic-tieng-anh-2024-da-thanh-cong-ruc-ro/",
    tags: ["học tập", "cuộc thi", "đrl"],
    drlCriteria: "Kỹ năng chuyên môn",
    drlPoints: 4,
    hasSeating: true,
    availableSeats: 40
  },
  {
    id: 6,
    type: "custom",
    image: "https://hiu.vn/wp-content/uploads/2024/10/SSS-870x285.jpg",
    title: "Talkshow Sức khỏe Tinh thần",
    time: "2025-07-05T14:00:00",
    location: "Online",
    description: "Chăm sóc tâm hồn, không ổn cũng oke!",
    eventType: "Talkshow",
    audience: "Sinh viên",
    readMoreUrl:
      "https://hiu.vn/hiu-student-center/talkshow-nang-cao-suc-khoe-tinh-than-cho-sinh-vien-voi-thong-diep-khong-on-cung-khong-sao/",
    tags: ["học tập", "kỹ năng", "đrl"],
    drlCriteria: "Kỹ năng chuyên môn",
    drlPoints: 3,
    hasSeating: false,
    isOnline: true,
    platform: "Zoom"
  },
  {
    id: 7,
    type: "custom",
    image: "https://hiu.vn/wp-content/uploads/2024/09/VS110-800x285.jpg",
    title: "Hướng dẫn viên Du lịch 2024",
    time: "2025-07-10T09:00:00",
    location: "Hội trường A, HIU",
    description: "Khám phá du lịch, nhận 3 ĐRL!",
    eventType: "Cuộc thi",
    audience: "Sinh viên",
    readMoreUrl:
      "https://hiu.vn/hiu-student-center/hiu-dong-to-chuc-huong-dan-vien-du-lich-trien-vong-toan-thanh-2024/",
    tags: ["học tập", "cuộc thi", "đrl"],
    drlCriteria: "Kỹ năng chuyên môn",
    drlPoints: 3,
    hasSeating: true,
    availableSeats: 25
  },
  {
    id: 8,
    type: "custom",
    image:
      "https://hiu.vn/wp-content/uploads/2024/06/447729001_424865507120950_2290725292462772115_n-870x285.jpg",
    title: "Tọa đàm Cải lương",
    time: "2025-07-15T17:00:00",
    location: "Hội trường Beethoven, HIU",
    description: "Đắm mình trong nghệ thuật cải lương!",
    eventType: "Hội thảo",
    audience: "Sinh viên",
    readMoreUrl:
      "https://hiu.vn/hiu-student-center/toa-dam-tim-hieu-am-nhac-dan-toc-hoc-duong-nghe-thuat-cai-luong-am-vang-hon-viet/",
    tags: ["giải trí", "văn hóa", "đrl"],
    drlCriteria: "Văn hóa",
    drlPoints: 2,
    hasSeating: true,
    availableSeats: 0 // Cháy vé
  },
  {
    id: 9,
    type: "custom",
    image: "https://hiu.vn/wp-content/uploads/2024/04/2-2-640x285.jpg",
    title: "Gala Talent Generation",
    time: "2025-07-20T18:00:00",
    location: "Sân vận động HIU",
    description: "Bùng nổ tài năng, đêm gala đỉnh cao!",
    eventType: "Festival",
    audience: "Sinh viên",
    readMoreUrl:
      "https://hiu.vn/hiu-student-center/san-sang-bung-no-cho-dem-gala-talent-generation-2024/",
    tags: ["giải trí", "festival", "đrl"],
    drlCriteria: "Văn hóa",
    drlPoints: 2,
    hasSeating: false
  },
  {
    id: 10,
    type: "custom",
    image:
      "https://hiu.vn/wp-content/uploads/2024/03/z5244900136193_31f8d00b8d1b713686b6955bfb7bd85b-800x285.jpg",
    title: "Rung Chuông Vàng 2024",
    time: "2025-07-25T09:00:00",
    location: "Hội trường A, HIU",
    description: "Thử tài Hàn Quốc, săn 4 ĐRL!",
    eventType: "Cuộc thi",
    audience: "Sinh viên",
    readMoreUrl:
      "https://hiu.vn/hiu-student-center/nhanh-tay-dang-ky-cuoc-thi-rung-chuong-vang/",
    tags: ["học tập", "cuộc thi", "đrl"],
    drlCriteria: "Kỹ năng chuyên môn",
    drlPoints: 4,
    hasSeating: true,
    availableSeats: 30
  },
  {
    id: 11,
    type: "custom",
    image: "https://hiu.vn/wp-content/uploads/2024/03/3-1-526x285.jpg",
    title: "King & Queen 2024",
    time: "2025-08-01T18:00:00",
    location: "Hội trường Beethoven, HIU",
    description: "Cặp đôi hoàn hảo, sân khấu rực rỡ!",
    eventType: "Cuộc thi",
    audience: "Sinh viên",
    readMoreUrl:
      "https://hiu.vn/hiu-student-center/king-queen-chinh-thuc-quay-tro-lai/",
    tags: ["giải trí", "cuộc thi", "đrl"],
    drlCriteria: "Văn hóa",
    drlPoints: 2,
    hasSeating: true,
    availableSeats: 0 // Cháy vé
  },
  {
    id: 12,
    type: "custom",
    image:
      "https://hiu.vn/wp-content/uploads/2024/03/rung-chuong-vang_07-03-2024-822x285.jpg",
    title: "Rung Chuông Vàng Hàn Quốc",
    time: "2025-08-05T09:00:00",
    location: "Hội trường A, HIU",
    description: "Khám phá Jeonlanam-do, săn 4 ĐRL!",
    eventType: "Cuộc thi",
    audience: "Sinh viên",
    readMoreUrl: "https://hiu.vn/hiu-student-center/cuoc-thi-rung-chuong-vang/",
    tags: ["học tập", "cuộc thi", "đrl"],
    drlCriteria: "Kỹ năng chuyên môn",
    drlPoints: 4,
    hasSeating: true,
    availableSeats: 35
  },
  {
    id: 13,
    type: "custom",
    image:
      "https://hiu.vn/wp-content/uploads/2023/06/Thie%CC%82%CC%81t-ke%CC%82%CC%81-kho%CC%82ng-te%CC%82n-10-800x285.png",
    title: "Chung kết Logistics Talent",
    time: "2025-08-10T14:00:00",
    location: "Hội trường A, HIU",
    description: "Tranh tài logistics, mở lối sự nghiệp!",
    eventType: "Cuộc thi",
    audience: "Sinh viên",
    readMoreUrl:
      "https://hiu.vn/hiu-student-center/top-6-doi-thi-tai-vong-chung-ket-cuoc-thi-hiu-logistics-talent-2023/",
    tags: ["học tập", "cuộc thi", "đrl"],
    drlCriteria: "Học tập",
    drlPoints: 4,
    hasSeating: true,
    availableSeats: 15
  },
  {
    id: 14,
    type: "custom",
    image: "https://hiu.vn/wp-content/uploads/2023/05/DSC00392-800x285.jpg",
    title: "HIU Startup: AraFace",
    time: "2025-08-15T18:00:00",
    location: "Hội trường Beethoven, HIU",
    description: "Chung kết khởi nghiệp, ý tưởng đỉnh cao!",
    eventType: "Cuộc thi",
    audience: "Sinh viên",
    readMoreUrl:
      "https://hiu.vn/hiu-student-center/du-an-bot-mat-na-araface-cua-dndn-gianh-chien-thang-tai-hiu-startup-2023/",
    tags: ["học tập", "cuộc thi", "khởi nghiệp", "đrl"],
    drlCriteria: "Học tập",
    drlPoints: 5,
    hasSeating: true,
    availableSeats: 0 // Cháy vé
  },
  {
    id: 15,
    type: "custom",
    image:
      "https://hiu.vn/wp-content/uploads/2023/05/Thie%CC%82%CC%81t-ke%CC%82%CC%81-kho%CC%82ng-te%CC%82n-8-800x285.png",
    title: "Olympic Tiếng Anh",
    time: "2025-08-20T09:00:00",
    location: "Hội trường A, HIU",
    description: "Rèn Tiếng Anh, săn 4 ĐRL!",
    eventType: "Cuộc thi",
    audience: "Sinh viên",
    readMoreUrl:
      "https://hiu.vn/hiu-student-center/nhung-khoanh-khac-an-tuong-cua-sinh-vien-nganh-ngon-ngu-anh-hiu-tai-cuoc-thi-olympic-tieng-anh/",
    tags: ["học tập", "cuộc thi", "đrl"],
    drlCriteria: "Kỹ năng chuyên môn",
    drlPoints: 4,
    hasSeating: true,
    availableSeats: 45
  },
  {
    id: 16,
    type: "custom",
    image:
      "https://images.unsplash.com/photo-1524178232363-1fb2b075b655?q=80&w=2070&auto=format&fit=crop",
    title: "Hội thảo Học bổng Du học",
    time: "2025-08-25T14:00:00",
    location: "Online",
    description: "Bí kíp săn học bổng, nhận 3 ĐRL!",
    eventType: "Hội thảo",
    audience: "Sinh viên",
    readMoreUrl: "#",
    tags: ["học tập", "học bổng", "đrl"],
    drlCriteria: "Hoạt động xã hội",
    drlPoints: 3,
    hasSeating: false,
    isOnline: true,
    platform: "Google Meet"
  },
  {
    id: 17,
    type: "custom",
    image:
      "https://images.unsplash.com/photo-1516321310766-61f6f7c0e96f?q=80&w=2070&auto=format&fit=crop",
    title: "Học bổng Lãnh đạo Trẻ",
    time: "2025-09-01T09:00:00",
    location: "Hội trường A, HIU",
    description: "Săn học bổng 50 triệu, nhận 5 ĐRL!",
    eventType: "Cuộc thi",
    audience: "Sinh viên",
    readMoreUrl: "#",
    tags: ["học tập", "học bổng", "cuộc thi", "đrl"],
    drlCriteria: "Kỹ năng chuyên môn",
    drlPoints: 5,
    hasSeating: true,
    availableSeats: 10
  },
  {
    id: 18,
    type: "custom",
    image:
      "https://images.unsplash.com/photo-1524178232363-1fb2b075b655?q=80&w=2070&auto=format&fit=crop",
    title: "Tư vấn Học bổng ASEAN",
    time: "2025-09-05T15:00:00",
    location: "Online",
    description: "Khám phá học bổng ASEAN, nhận 3 ĐRL!",
    eventType: "Hội thảo",
    audience: "Sinh viên",
    readMoreUrl: "#",
    tags: ["học tập", "học bổng", "đrl"],
    drlCriteria: "Hoạt động xã hội",
    drlPoints: 3,
    hasSeating: false,
    isOnline: true,
    platform: "Zoom"
  },
  {
    id: 19,
    type: "custom",
    image:
      "https://images.unsplash.com/photo-1516321310766-61f6f7c0e96f?q=80&w=2070&auto=format&fit=crop",
    title: "Học bổng Khởi nghiệp",
    time: "2025-09-10T08:00:00",
    location: "Hội trường Beethoven, HIU",
    description: "Ý tưởng khởi nghiệp, săn 5 ĐRL!",
    eventType: "Cuộc thi",
    audience: "Sinh viên",
    readMoreUrl: "#",
    tags: ["học tập", "học bổng", "cuộc thi", "khởi nghiệp", "đrl"],
    drlCriteria: "Học tập",
    drlPoints: 5,
    hasSeating: true,
    availableSeats: 0 // Cháy vé
  },
  {
    id: 20,
    type: "custom",
    image:
      "https://images.unsplash.com/photo-1524178232363-1fb2b075b655?q=80&w=2070&auto=format&fit=crop",
    title: "Hội thảo Chevening",
    time: "2025-09-15T14:00:00",
    location: "Hội trường A, HIU",
    description: "Du học Anh Quốc, nhận 3 ĐRL!",
    eventType: "Hội thảo",
    audience: "Sinh viên",
    readMoreUrl: "#",
    tags: ["học tập", "học bổng", "đrl"],
    drlCriteria: "Hoạt động xã hội",
    drlPoints: 3,
    hasSeating: true,
    availableSeats: 50
  }
];

export default events;
